###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################

version: "3.1"

services:
    mysql:
      image: mysql:5.7
      container_name: wordpress-mysql
      working_dir: /application
      volumes:
        - ./application:/application
      environment:
        - MYSQL_ROOT_PASSWORD=developer
        - MYSQL_DATABASE=developer
        - MYSQL_USER=developer
        - MYSQL_PASSWORD=developer
      ports:
        - "8082:3306"
      
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: wordpress-phpmyadmin
        environment:
        - PMA_ARBITRARY=1
        restart: always
        ports:
        - 9091:80
        volumes:
        - /sessions
        links:
        - mysql:db
        depends_on:
        - mysql

    webserver:
      image: nginx:alpine
      container_name: wordpress-webserver
      working_dir: /application
      volumes:
          - ./application:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "9090:80"
      links:
      - mysql:db       

    php-fpm:
      build: phpdocker/php-fpm
      container_name: wordpress-php-fpm
      working_dir: /application
      volumes:
        - ./application:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
      links:
        - mysql:db

